###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
import numpy as np
n = np.random.randint(1,100,(4,3))
n

array([[61, 53, 87],
       [97, 75, 62],
       [26, 31, 14],
       [81, 44, 20]])

In [ ]:
# sort
np.sort(n)

array([[53, 61, 87],
       [62, 75, 97],
       [14, 26, 31],
       [20, 44, 81]])

In [ ]:
#Based on 2nd column
# n[np.argsort(n[:,1])]
print(n[n[:,1].argsort()])

array([[26, 31, 14],
       [81, 44, 20],
       [61, 53, 87],
       [97, 75, 62]])

In [ ]:
# Sort this matrix based on max value in each row.
print(np.array(sorted(n,key = lambda x:max(x))))

[[26 31 14]
 [81 44 20]
 [61 53 87]
 [97 75 62]]


In [ ]:
# sorted by value
print(np.sort(n,axis= None).reshape(4,3))

[[14 20 26]
 [31 44 53]
 [61 62 75]
 [81 87 97]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92])

In [ ]:
#1.
extra = np.expand_dims(extra_subject,axis = 1)
marks = np.concatenate((marks,extra),axis = 1)
print(marks)

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]


In [ ]:
#2
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)
# print(rec1)
# print(rec2)
updated_marks = np.concatenate((marks,rec1,rec2),axis = 0)
print(updated_marks)

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]


In [ ]:
#3
# sum = np.cumsum(updated_marks,axis = 1).reshape(7,5)[:,-1].reshape(-1,1)
# print(sum)
sum = np.sum(updated_marks,axis = 1,keepdims=True)
# print(sum)
total = np.concatenate((updated_marks,sum),axis = 1)
total

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [ ]:
#4
# n = (total[total[:,-1].argsort()[::-1]])
# print(n[:2])

print(np.array(sorted(total,key = lambda x: x[-1],reverse = True)[:2]))

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])


In [ ]:
print(np.unique(arr,axis = 0))
print(np.unique(arr,axis = 1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
n = np.random.randint(1,100,(5,4))
n

array([[76, 29, 88, 69],
       [65, 17, 80, 44],
       [27, 90, 82,  2],
       [98, 12, 81, 71],
       [ 5, 50, 67, 58]])

In [ ]:
print(np.flip(n))

[[76 29 88 69]
 [65 17 80 44]
 [27 90 82  2]
 [98 12 81 71]
 [ 5 50 67 58]]
[[69 88 29 76]
 [44 80 17 65]
 [ 2 82 90 27]
 [71 81 12 98]
 [58 67 50  5]]



### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
arr =np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

x = 6
print(np.where(np.any(arr > 6,axis = 1)))

(array([1, 3]),)


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [ ]:
np.concatenate((arr1,arr2,arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
# print(np.sort(arr))
# print(np.sort(arr)[0,1:-1])4

max = np.argmax(arr)
min = np.argmin(arr)
print(arr.max())
print(arr.min())
arr = np.delete(arr,max,axis = 1)
arr = np.delete(arr,min,axis = 1)
print(arr)

print(arr.max(),arr.min())


998
103
[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
  323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
  270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
  620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
  426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
  922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
  695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
  761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]]
997 117


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
arr = np.random.randint(1,200,100)
print(np.cumsum(np.sort(np.clip(arr,a_min=100,a_max=200))))

[  100   200   300   400   500   600   700   800   900  1000  1100  1200
  1300  1400  1500  1600  1700  1800  1900  2000  2100  2200  2300  2400
  2500  2600  2700  2800  2900  3000  3100  3200  3300  3400  3500  3600
  3700  3800  3900  4000  4100  4200  4300  4400  4500  4600  4700  4800
  4900  5000  5101  5207  5314  5421  5530  5639  5748  5858  5970  6083
  6202  6322  6443  6564  6687  6811  6936  7063  7192  7323  7455  7588
  7724  7860  8003  8147  8294  8442  8594  8748  8903  9060  9219  9379
  9543  9709  9875 10045 10215 10391 10571 10756 10945 11138 11331 11527
 11723 11920 12117 12316]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [ ]:
a = np.random.random(100)
a = np.around(a,decimals=3)
a

array([0.466, 0.383, 0.435, 0.888, 0.147, 0.136, 0.914, 0.867, 0.839,
       0.299, 0.366, 0.284, 0.937, 0.439, 0.822, 0.902, 0.676, 0.102,
       0.901, 0.122, 0.56 , 0.194, 0.994, 0.985, 0.474, 0.268, 0.294,
       0.883, 0.24 , 0.996, 0.995, 0.618, 0.256, 0.775, 0.965, 0.77 ,
       0.416, 0.52 , 0.669, 0.509, 0.749, 0.154, 0.39 , 0.783, 0.644,
       0.294, 0.075, 0.737, 0.665, 0.172, 0.989, 0.151, 0.223, 0.83 ,
       0.112, 0.045, 0.295, 0.269, 0.294, 0.507, 0.332, 0.672, 0.817,
       0.228, 0.892, 0.671, 0.731, 0.436, 0.272, 0.701, 0.052, 0.939,
       0.507, 0.812, 0.137, 0.906, 0.415, 0.556, 0.758, 0.427, 0.949,
       0.539, 0.826, 0.924, 0.487, 0.36 , 0.632, 0.401, 0.627, 0.455,
       0.782, 0.147, 0.022, 0.439, 0.411, 0.378, 0.634, 0.889, 0.048,
       0.465])

In [ ]:
print(f"0th percentile == minimum value of the array is {np.percentile(a,0) == a.min()}")
print(f"100th percentile == minimum value of the array is {np.percentile(a,100) == a.max()}")
print(f"The difference betwen 51th percenile and 50th percentile values {np.percentile(a,51) - np.percentile(a,50)}")

0th percentile == minimum value of the array is True
100th percentile == minimum value of the array is True
The difference betwen 51th percenile and 50th percentile values 0.0009799999999999809
