### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
np.sort(a)

array([ 4, 12, 15, 17, 20, 36, 43, 44, 44, 51, 74, 77, 83, 91, 95])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
np.sort(b,axis = 1) #-> row wise

array([[15, 32, 63, 94],
       [36, 50, 53, 91],
       [16, 18, 30, 36],
       [14, 40, 47, 95],
       [24, 34, 65, 93],
       [12, 67, 91, 93]])

In [4]:
np.sort(a)[::-1] # decending order

array([78, 77, 74, 74, 73, 71, 58, 45, 41, 37, 31, 24, 20, 17, 15])

In [5]:
np.sort(b,axis=0) #-> column wise

array([[12, 14, 15, 16],
       [30, 18, 24, 36],
       [32, 34, 36, 40],
       [47, 50, 91, 63],
       [53, 93, 91, 67],
       [65, 94, 95, 93]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
np.append(a,200)


array([ 20,  71,  31,  78,  17,  58,  15,  77,  45,  74,  37,  24,  74,
        73,  41, 200])

In [9]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[32., 94., 15., 63.,  1.],
       [53., 50., 91., 36.,  1.],
       [30., 18., 36., 16.,  1.],
       [47., 14., 95., 40.,  1.],
       [65., 34., 24., 93.,  1.],
       [12., 93., 91., 67.,  1.]])

In [10]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[32.        , 94.        , 15.        , 63.        ,  0.9688985 ],
       [53.        , 50.        , 91.        , 36.        ,  0.19165449],
       [30.        , 18.        , 36.        , 16.        ,  0.11138908],
       [47.        , 14.        , 95.        , 40.        ,  0.44831447],
       [65.        , 34.        , 24.        , 93.        ,  0.59659811],
       [12.        , 93.        , 91.        , 67.        ,  0.58793593]])

In [17]:
b.shape[0] #-> rows count
b.shape[1] #-> columns count

4

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [18]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [23]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [24]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [27]:
# code
a.shape

(15,)

In [29]:
np.expand_dims(a, axis = 0).shape

(1, 15)

In [28]:
np.expand_dims(a,axis=1)

array([[20],
       [71],
       [31],
       [78],
       [17],
       [58],
       [15],
       [77],
       [45],
       [74],
       [37],
       [24],
       [74],
       [73],
       [41]])

In [31]:
np.expand_dims(a,axis = 1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [32]:
a

array([20, 71, 31, 78, 17, 58, 15, 77, 45, 74, 37, 24, 74, 73, 41])

In [34]:
# find all indices with value greater than 50
np.where(a>50)
a[np.where(a>50)]

array([71, 78, 58, 77, 74, 74, 73])

In [35]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([20,  0, 31,  0, 17,  0, 15,  0, 45,  0, 37, 24,  0,  0, 41])

In [36]:
np.where(a%2 == 0,0,a) #-> replace even number with zero.

array([ 0, 71, 31,  0, 17,  0, 15, 77, 45,  0, 37,  0,  0, 73, 41])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [37]:
# code
a

array([20, 71, 31, 78, 17, 58, 15, 77, 45, 74, 37, 24, 74, 73, 41])

In [38]:
np.argmax(a)

3

In [41]:
b

array([[32, 94, 15, 63],
       [53, 50, 91, 36],
       [30, 18, 36, 16],
       [47, 14, 95, 40],
       [65, 34, 24, 93],
       [12, 93, 91, 67]])

In [43]:
np.argmax(b,axis=0)

array([4, 0, 3, 4])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [44]:
# np.argmin
np.argmin(a)

6

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 12,  64, 106, 112],
       [ 29,  47,  94, 149],
       [ 61, 154, 237, 246],
       [ 38, 101, 145, 230],
       [  8,  95, 126, 198],
       [ 40, 111, 113, 120]])

In [ ]:
np.cumsum(b) #-> change the 2D to 1D

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [45]:
a

array([20, 71, 31, 78, 17, 58, 15, 77, 45, 74, 37, 24, 74, 73, 41])

In [52]:
np.percentile(a,5 0)

45.0

In [48]:
np.median(a)

45.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [57]:
# code
a

array([20, 71, 31, 78, 17, 58, 15, 77, 45, 74, 37, 24, 74, 73, 41])

In [56]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 2, 2, 2, 1, 0, 6, 0, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [59]:
# code
a


array([20, 71, 31, 78, 17, 58, 15, 77, 45, 74, 37, 24, 74, 73, 41])

In [60]:
items = [10,20,30,40,50,60,70,80,90,100]
print(np.isin(a,items))
a[np.isin(a,items)]

[ True False False False False False False False False False False False
 False False False]


array([20])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [63]:
print(b)
np.flip(b)

[[32 94 15 63]
 [53 50 91 36]
 [30 18 36 16]
 [47 14 95 40]
 [65 34 24 93]
 [12 93 91 67]]


array([[67, 91, 93, 12],
       [93, 24, 34, 65],
       [40, 95, 14, 47],
       [16, 36, 18, 30],
       [36, 91, 50, 53],
       [63, 15, 94, 32]])

In [ ]:
np.flip(b,axis=1)

array([[ 6, 42, 52, 12],
       [55, 47, 18, 29],
       [ 9, 83, 93, 61],
       [85, 44, 63, 38],
       [72, 31, 87,  8],
       [ 7,  2, 71, 40]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [64]:
# code
a

array([20, 71, 31, 78, 17, 58, 15, 77, 45, 74, 37, 24, 74, 73, 41])

In [65]:
c= np.put(a,[0,1],[110,530])

In [68]:
a

array([110, 530,  31,  78,  17,  58,  15,  77,  45,  74,  37,  24,  74,
        73,  41])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [69]:
np.delete(a,[0,1])

array([31, 78, 17, 58, 15, 77, 45, 74, 37, 24, 74, 73, 41])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [3]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
np.intersect1d(m,n)

array([3, 4, 5])

In [5]:
np.setdiff1d(n,m)

array([6, 7])

In [6]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [7]:
np.clip(a,a_min=25,a_max=75)

array([44, 43, 51, 75, 25, 36, 25, 25, 75, 25, 74, 25, 44, 75, 75])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals

In [9]:
import numpy as np
a = np.array([1,2,3])
np.repeat(a,5)
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])