In [3]:
import numpy as np  #Numpy library
n = np.array([1,2,3]) # 1D array
print(n)
type(n)

[1 2 3]


numpy.ndarray

In [4]:
nd = np.array([[1,2,3],[2,4,5]]) #2D array
print(nd)

[[1 2 3]
 [2 4 5]]


In [5]:
nd = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3d array
print(nd)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
n = np.array([1,2,3],dtype = float)
print(n)

n = np.array([1,2,3],dtype = bool) #Any non zero is true is python
print(n)

n = np.array([1,2,3],dtype = complex)
print(n)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [29]:
b= np.arange(1,11) #range function in numpy
b= np.arange(30,11,-2 )
b= np.arange(1,17).reshape(2,2,2,2) #3D array
print(b)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [14]:
c = np.arange(1,13).reshape(4,3) #Reshape(4 row and three columns)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.random.random((3,3))

array([[0.65819373, 0.88804229, 0.15655711],
       [0.96102639, 0.52850176, 0.79539651],
       [0.47780987, 0.49926971, 0.69873418]])

In [25]:
np.linspace(-10,10,10) #Linear space. (equal distance points)
np.linspace(-10,10,10).reshape(5,2) # It will also work.

array([[-10.        ,  -7.77777778],
       [ -5.55555556,  -3.33333333],
       [ -1.11111111,   1.11111111],
       [  3.33333333,   5.55555556],
       [  7.77777778,  10.        ]])

In [22]:
np.identity(3) #It prints diagonally 1 and other values are 0.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Attributes

In [45]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12,dtype = float).reshape(4,3)
a3 = np.arange(8).reshape(2,2,2)

In [33]:
 # ndim
a2.ndim
a1.ndim
a3.ndim

3

In [36]:
# shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [39]:
#size
a1.size
a2.size
a3.size

8

In [46]:
#item size
print(a1.itemsize) #int 32 = 4 bytes,int64 = 8 bytes
a2.itemsize
a3.itemsize

4


8

In [47]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


change datatype

In [54]:
# astype
a3.astype(np.int32) #changing datatype
a1.astype(np.int64) # changes the storage memory and save memory.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# array operations

In [56]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)


In [60]:
# scaler operations
#arithmatic
print(a1 * 2)
print(a1 + 2)
print(a1 ** 2)
print(a1 / 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [64]:
# Reational operator
a1 > 5
a1 < 5
a2 >= 20

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [65]:
# Vector operations
#arithmatic
a1 + a2 (all will work)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [68]:
a1 * a2
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Functions

In [90]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1.astype(np.int32)


array([[47, 81,  3],
       [87,  2, 70],
       [ 6, 40, 16]], dtype=int32)

In [77]:
# max,sum,min,prod
np.max(a1)
np.sum(a1)
np.min(a1)
np.prod(a1)

232444923110400.0

In [79]:
# these function accourding to the row and columns
# here 0 is column and 1 is row
print(np.max(a1,axis = 0)) #by column
print(np.max(a1,axis = 1)) # by row
print(np.min(a1,axis = 0))
print(np.min(a1,axis = 1))

[74. 95. 44.]
[74. 44. 95.]
[44. 13. 16.]
[44. 13. 23.]


In [82]:
# mean/median/std/var
print(a1)
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

[[74. 51. 44.]
 [44. 13. 16.]
 [70. 95. 23.]]
47.77777777777778
44.0
26.422960460670808
698.1728395061729


In [83]:
# trignometric
np.sin(a1)

array([[-0.98514626,  0.67022918,  0.01770193],
       [ 0.01770193,  0.42016704, -0.28790332],
       [ 0.77389068,  0.68326171, -0.8462204 ]])

In [85]:
# Dot product -> first matric col and second matrix row must have same shape.
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
print(np.dot(a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [87]:
# log and exponents
np.log(a1)

array([[4.30406509, 3.93182563, 3.78418963],
       [3.78418963, 2.56494936, 2.77258872],
       [4.24849524, 4.55387689, 3.13549422]])

In [88]:
np.exp(a1)

array([[1.37338298e+32, 1.40934908e+22, 1.28516001e+19],
       [1.28516001e+19, 4.42413392e+05, 8.88611052e+06],
       [2.51543867e+30, 1.81123908e+41, 9.74480345e+09]])

In [96]:
# round/ciel/floor
a4 = np.round(np.random.random((3,4))* 100)
print(a4)

a4 = np.ceil(np.random.random((3,4))* 100)
print(a4)

a4 = np.floor(np.random.random((3,4))* 100)
print(a4)

[[59. 92. 59. 53.]
 [22.  1. 67. 21.]
 [69. 83. 18. 21.]]
[[56. 68.  6. 76.]
 [67. 73. 95. 39.]
 [73. 31. 55. 37.]]
[[56. 97. 14. 92.]
 [96. 36. 95.  3.]
 [76. 37. 23. 55.]]


# Indexing slicing

In [98]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [100]:
a1[5] - #1d array

5

In [103]:
# 2d array
a2[0,3]
a2[2,2]
a2[2,3]

11

In [106]:
# 3d array
a3[0,0,0]
a3[1,0,1]
a3[1,1,1]

7

In [128]:
# slicing
a1[0:5] #1d array
a1[-1::-1]
a1[0::2]


array([0, 2, 4, 6, 8])

In [113]:
print(a2)
a2[1,0:] #2d array slicing
a2[2,1:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 9, 10, 11])

In [122]:
a2[0,:]
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [135]:
a2[1:2,0::3]

array([[4, 7]])

In [138]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [123]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [124]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [114]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [119]:
a3[1,1,0:] #slicing
a3[0,1,1:]
a3[0,1,0:]

array([2, 3])

In [140]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [142]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [143]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [149]:
# print(a3)
a3[1,:,1]

array([10, 13, 16])

In [150]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [152]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [154]:
# print(a3)
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [156]:
for i in a2:
  print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [157]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [158]:
for i in np.nditer(a3): #way to print each time from ever dimensional array.
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshape

In [160]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [162]:
#ravel #convert any array to 1D
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [164]:
#Horizental
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [165]:
#horizental
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [167]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Spliting

In [169]:
# Horizentally
print(a4)
np.hsplit(a4,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [171]:
#Verically
print(a5)
np.vsplit(a5,3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]